#!/usr/bin/env bash
# Installs and configures HAProxy on a load balancer server.

# Set bash unofficial strict mode
set -euo pipefail
IFS=$'\n\t'

# Ensures the script executes operations with superuser privileges
sudo -v

# Update system and install necessary packages
echo "Installing necessary packages..."
sudo apt-get update && sudo apt-get install -y software-properties-common

# Add the official HAProxy PPA (uncomment if needed, might require specific Ubuntu versions)
# sudo add-apt-repository -y ppa:vbernat/haproxy

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Enable HAProxy to start on boot
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Backup the current HAProxy configuration
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original

# Create a new HAProxy configuration file
echo "Configuring HAProxy..."
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 530845-web-01 54.236.8.64:80 check
    server 530845-web-02 100.24.72.30:80 check
EOF

# Restart HAProxy to apply the configuration
sudo systemctl restart haproxy
sudo systemctl enable haproxy
echo "HAProxy has been configured and restarted."
