#!/usr/bin/env bash
# Installs and configures HAProxy on a load balancer server.

# Set bash unofficial strict mode
set -euo pipefail
IFS=$'\n\t'

# Ensures the script executes operations with superuser privileges
sudo -v

# Update system and install necessary packages
echo "Installing necessary packages..."
sudo apt-get update && sudo apt-get install -y software-properties-common haproxy

# Enable HAProxy to start on boot and ensure it is enabled
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

# Backup the current HAProxy configuration
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original

# Create a new HAProxy configuration file
echo "Configuring HAProxy..."
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server web-01 54.236.8.64:80 check
    server web-02 100.24.72.30:80 check
EOF

# Restart HAProxy to apply the configuration
echo "Restarting HAProxy..."
sudo systemctl restart haproxy
sudo systemctl enable haproxy
echo "HAProxy has been configured and restarted. It is now balancing requests between web-01 and web-02."

# Verify configuration and check for the mention of web servers in the startup logs
echo "Verifying HAProxy configuration..."
sudo haproxy -c -V -f /etc/haproxy/haproxy.cfg
echo "Configuration check complete."

# Outputting final server checks to ensure servers are recognized
echo "HAProxy is configured to balance traffic between the following servers:"
grep 'server web' /etc/haproxy/haproxy.cfg | awk '{print $2 " at IP: " $3}'
