#!/usr/bin/env bash
# What is preventing the Nginx installation from listening to port 80?
# Configure nginx to run and listen to port 80.

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart