#!/usr/bin/env bash
# Changes port in Nginx configuration and restarts the service

# Change the server port from 8080 to 80 in the Nginx configuration
sudo sed -i 's/listen 8080;/listen 80;/g' /etc/nginx/sites-enabled/default

# Restart the Nginx service to apply changes
sudo systemctl restart nginx
