#!/usr/bin/env bash
# Changes port in Nginx configuration and restarts the service if not running
sudo sed -i 's/listen 8080;/listen 80;/g' /etc/nginx/sites-enabled/default
sudo service nginx status | grep -q "nginx is running" || sudo service nginx restart


