#!/usr/bin/env bash
# Fixes the issue with the server
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-enabled/*
sed -i 's/listen \[::\]:80;/listen [::]:8080;/' /etc/nginx/sites-enabled/*
service nginx stop
service nginx start
