name: Make Files Executable

on:
  push:
    branches:
      - master

jobs:
  make-executable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make files executable
        run: |
          chmod +x 0x16-api_advanced/100-count.py
          chmod +x 0x16-api_advanced/0-subs.py
          chmod +x 0x16-api_advanced/1-top_ten.py
          chmod +x 0x16-api_advanced/2-recurse.py
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add 0x16-api_advanced/100-count.py
          git add 0x16-api_advanced/0-subs.py
          git add 0x16-api_advanced/1-top_ten.py
          git add 0x16-api_advanced/2-recurse.py
          git commit -m 'Make 0x16-api_advanced files executable'
          git push
