#!/usr/bin/env bash
# Reload Gunicorn gracefully without downtime

pid=$(pgrep -f 'gunicorn')
if [ -n "$pid" ]; then
    kill -HUP $pid
    echo "Gunicorn gracefully reloaded."
else
    echo "Gunicorn is not running."
fi
