#!/usr/bin/env bash
# Reload Gunicorn gracefully without downtime

pids=$(pgrep -f 'gunicorn')
if [ -n "$pids" ]; then
    echo "$pids" | xargs kill -HUP
    echo "Gunicorn gracefully reloaded."
else
    echo "Gunicorn is not running."
fi
